### ISSUE TITLE
Último dado é de 20/10/2016

### ISSUE THREAD

**Issue by chicobjr** [aparabolica/mananciais#6]
O último valor dos níveis dos mananciais é de 20/10/2016. Hoje é dia 16/11/2016.
Esse site http://mananciais.tk é muito útil, parabéns pelo trabalho.

**Comment by miguelpeixe** [comment]
Obrigado pelo report @chicobjr . O problema já foi solucionado.

**Comment by miguelpeixe** [comment]
A SABESP está com algum novo mecanismo que impede a atualização em massa de dados (para recuperar todos os dias perdidos de uma vez). Estamos investigando como contornar.

**Comment by chicobjr** [comment]
@miguelpeixe , vi que o assunto não evoluiu. Se o problema for somente atualização dos dias perdidos, podemos fazer uma task-force e pegar manualmente esses dados, entendo que o último dado válido é de 20/Outubro/2016. Estou à disposição.

**Comment by amartini** [comment]
Olá, encontrei o problema. é só por 
      'Upgrade-Insecure-Requests': '1'
Na linha 123 do scrape.js
@miguelpeixe

**Comment by miguelpeixe** [comment]
@amartini aqui não funcionou, apliquei primeiro à linha 123, e depois também à linha 153. Nenhuma alteração no resultado. Ele segue retornando um cache do último dado, sem considerar os parâmetros do formulário.

**Comment by amartini** [comment]
uai.. tenta por isso na linha 265

		'__VIEWSTATEENCRYPTED': html('#__VIEWSTATEENCRYPTED').val(),

**Comment by amartini** [comment]
@miguelpeixe 
Reforçando que consegui baixar os dados com essas modificações.
Segue o CSV que obtive:
[data.zip](https://github.com/aparabolica/mananciais/files/768278/data.zip)
